#page title
page_title: Hotly:Dating AI Characters

# App Info
ios_app_id: 1234793120 # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country: us # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link: "" # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link: # Enter Google Play Store URL.
presskit_download_link:

app_icon: assets/appicon.png # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name: Hotly # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price: # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description: Experience AI romance with Hotly! Chat with unique AI characters, build virtual relationships, and explore digital love. Your perfect AI date is just a tap away!

enable_smart_app_banner: true # Set to true to show a smart app banner at top of page on mobile devices.

# Information About Yourself
your_name: Hotly
your_link: https://hotly.hugosoftware.net/
your_city: Istanbul, Turkey
email_address: supporthotly@hugosoftware.net
facebook_username:
instagram_username: hugosoftware
twitter_username: hugosoftware
github_username: hugosoftware
youtube_username:
mastodon_link: ""

# Feature List                            Edit, add or remove features to be presented.
features:
  - title: Smart Matching Algorithms
    description: Smart algorithms effortlessly find your perfect match.
    fontawesome_icon_name: heart

  - title: AI-Enhanced Conversations
    description: AI understands feelings, enhancing your conversations.
    fontawesome_icon_name: comments

  - title: Immersive AI Environments
    description: Experience unique encounters in immersive AI environments.
    fontawesome_icon_name: vr-cardboard

  - title: Personalized Dating Advice
    description: Tailored advice boosts your dating confidence.
    fontawesome_icon_name: user-friends

  - title: Voice Call Feature
    description: Connect with AI characters through immersive voice calls.
    fontawesome_icon_name: phone

  - title: Diverse AI Personalities
    description: Explore a wide range of unique AI characters and personalities.
    fontawesome_icon_name: robot

  - title: # New Feature Title
    description: # New Feature Description
    fontawesome_icon_name: # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.

# Theme Settings
topbar_color: "#000000"
topbar_transparency: 0.1
topbar_title_color: "#ffffff"

cover_image: assets/headerimage.png # Replace with alternative image path or image URL.
cover_overlay_color: "#363b3d"
cover_overlay_transparency: 0.8

device_color: black # Set to: blue, black, yellow, coral or white.

body_background_color: "#ffffff"

link_color: "#E91E63"

app_title_color: "#ffffff"
app_price_color: "#ffffff"
app_description_color: "#ffffff"

feature_title_color: "#000000"
feature_text_color: "#666666"

feature_icons_foreground_color: "#E91E63"
feature_icons_background_color: "#f5f5f5"

social_icons_foreground_color: "#666666"
social_icons_background_color: "#e6e6e6"

footer_text_color: "#666666"

####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
